const CardTheme = {
  '--card-padding': '0px 0 15px 0',
  '--card-background': '#fff',
  '--card-border-radius': '4px',
  '--card-image-width': '100%',
  '--card-row-image-width': '140px',
  '--card-image-height': '200px',
  '--card-row-height': '140px',
  '--card-title-color': '#333',
  '--card-title-font-size': '20px',
  '--card-title-padding': '0 12px',
  '--card-title-margin': '15px 0 0 0',
  '--card-title-row-margin': '12px 0',
  '--card-subtitle-color': 'rgba(0, 0, 0, 0.6)',
  '--card-subtitle-font-size': '14px',
  '--card-subtitle-padding': '0 13px',
  '--card-subtitle-margin': '10px 0 0 0',
  '--card-subtitle-row-margin': '-8px 0 0 0',
  '--card-description-color': 'rgba(0, 0, 0, 0.6)',
  '--card-description-font-size': '14px',
  '--card-description-margin': '20px 0 0 0',
  '--card-description-padding': '0 13px',
  '--card-footer-padding': '0 12px',
  ' --card-footer-right': '30px 0 0px 0',
  '--card-footer-bottom': '13px',
  '--card-footer-margin': '9px',
  '--card-line-height': '22px',
  '--card-row-line-height': '1.5',
  '--card-floating-buttons-bottom': '16px',
  '--card-floating-buttons-right': '16px',
  '--card-floating-buttons-color': '#fff',
  '--card-close-button-icon-size': '24px',
  '--card-close-button-size': '56px',
  '--card-close-button-primary-color': '#212121',
}

export default CardTheme
