const TimePickerTheme = {
  '--time-picker-border-radius': '4px',
  '--time-picker-font-size': 'var(--font-size-md)',
  '--time-picker-min-width': '290px',
  '--time-picker-height': '385px',
  '--time-picker-title-padding': '16px',
  '--time-picker-title-color': '#fff',
  '--time-picker-title-background': 'var(--color-primary)',
  '--time-picker-title-time-font-size': '50px',
  '--time-picker-title-time-margin': '0 5px',
  '--time-picker-title-ampm-margin-left': '5px',
  '--time-picker-clock-left': '27px',
  '--time-picker-clock-right': '27px',
  '--time-picker-clock-top': '27px',
  '--time-picker-clock-bottom': '27px',
  '--time-picker-clock-container-width': '270px',
  '--time-picker-clock-container-height': '270px',
  '--time-picker-clock-container-background': '#e0e0e0',
  '--time-picker-clock-hand-height': 'calc(50% - 4px)',
  '--time-picker-clock-hand-width': '2px',
  '--time-picker-clock-hand-bottom': '50%',
  '--time-picker-clock-hand-left': 'calc(50% - 1px)',
  '--time-picker-clock-hand-background': 'var(--color-primary)',
  '--time-picker-clock-hand-border-color': 'var(--color-primary)',
  '--time-picker-clock-hand-before-width': '10p',
  '--time-picker-clock-hand-before-height': '10px',
  '--time-picker-clock-hand-before-border-width': '2px',
  '--time-picker-clock-hand-after-width': '4px',
  '--time-picker-clock-hand-after-height': '4px',
  '--time-picker-clock-item-height': '32px',
  '--time-picker-clock-item-width': '32px',
  '--time-picker-clock-item-active-background': 'var(--color-primary)',
  '--time-picker-clock-item-active-color': '#fff',
  '--time-picker-clock-item-disable-color': 'rgba(0, 0, 0, 0.26)',
  '--time-picker-inner-left': '36px',
  '--time-picker-inner-right': '36px',
  '--time-picker-inner-top': '36px',
  '--time-picker-inner-bottom': '36px',
  '--time-picker-body-background': 'transparent',
}

export default TimePickerTheme
